### ISSUE TITLE
Email monitoring / notifications

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-metrics#2]
Build in some basic error handling with email notifications included. Especially useful to catch things like lost authentication between the app and google analytics for example.

**Comment by jdotpz** [comment]
Ah, we'll need to choose an email address to send from for staging/prod (likely same addy?), and get an inbox setup as a dist list and get it on SES.

**Comment by adamlofting** [comment]
Ah, thanks. I'd been thinking of building this at an App level, but an Ops level is even better :smile: 

We can definitely use a single email address for both staging and prod.
