### ISSUE TITLE
Reveal metrics

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-metrics#21]
Maybe old news to @adamlofting, and definitely not essential, but I thought that this was a nice way to surface info, to both the general public and staff trying to understand their impact. 

On Gov.uk, add /info/ before any page uri to reveal metrics. Example:
 - https://www.gov.uk/renew-driving-licence
 - https://www.gov.uk/info/renew-driving-licence

**Comment by adamlofting** [comment]
Yeah, I love those pages. :+1: 

Not just the numbers but also the clearly defined purpose for the page: 

> "The user need for this page:..."

**Comment by davidascher** [comment]
That site is in general an amazing role model.
