### ISSUE TITLE
Needs to automatically bump to https

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-metrics#35]
metrics.webmaker.org doesn't automatically bump me up to https. DNS never resolves – eventually just times out. Need to manually enter "https://".

cc @jbuck

**Comment by adamlofting** [comment]
Any help would be welcome on this. I haven't had time to debug this yet.

This works on Heroku when I was prototyping this, but not on our AWS setup: 
https://github.com/adamlofting/webmaker-metrics/blob/master/app.js#L566-L582

Might be something todo with the setting for proxy https used here: https://github.com/adamlofting/webmaker-metrics/blob/master/app.js#L37 (though removing the `true` stopped the app working altogether).

**Comment by jbuck** [comment]
The problem was that the mofometrics-ec2-sg security group was not configured to allow inbound port 8080

**Comment by adamlofting** [comment]
Awesome :+1: I'd never have worked that out :stuck_out_tongue_winking_eye:
