### ISSUE TITLE
Add # of retained users to the dashboard

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-metrics#40]
Alongside the retention rates, also show the number of users retained beyond 7 days, 30 days, 90 days.

cc @thisandagain

**Comment by adamlofting** [comment]
These KPIs have been added to:
https://metrics.webmaker.org/dashboard/product-kpis

Via: https://github.com/mozilla/webmaker-metrics/pull/41

**Comment by thisandagain** [comment]
Thanks Adam!
