### ISSUE TITLE
Add team to GA

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-metrics#45]
Give team members access to view analytics

**Comment by adamlofting** [comment]
Most people have this already, but I think they forget the url: http://www.google.com/analytics

Can you let me know anyone who's missing and I can add them.

**Comment by thisandagain** [comment]
I believe @gvn was having trouble getting access yesterday.

**Comment by adamlofting** [comment]
Thanks, @gvn is in now.

I'll leave this ticket open for now in case anyone else gets stuck.
