### ISSUE TITLE
Initial code review of webmaker-metrics

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-metrics#6]
Thanks for helping with this. I've tried to write a readme for this app that explains what it does and why, and what's needed for development. Hopefully that's a good starting point for you.

There's a chunk of in-progress work in this around a RIDs dashboard. For the sake of this review, if you focus on the webmaker product KPI dashboard I'll apply the same feedback to the RIDs logic and dashboard when I work further on that.

I'll send you creds for a readonly version of the `mofointegration` database used in the app, but the data will be a few days out of date when you crunch the numbers. 

You also need to auth the app against GA - do you have GA access to the Webmaker profile for testing this?

`crunch.js` was going to be scheduled to run daily in Heroku, so it's scrappy at the moment. I'll tidy this up once I know what the new hosting looks like.

Any feedback is welcome: architecture, structure, good/bad design, documentation etc... 

As I've been working on my own on this, I'm sure I've fallen into some bad habits. :scream:

**Comment by cadecairos** [comment]
https://github.com/mozilla/webmaker-metrics/blob/master/app.js#L139

extraTemplateValues and its accompanying code don't appear to ever get used, can it be axed?

**Comment by cadecairos** [comment]
https://github.com/mozilla/webmaker-metrics/blob/master/app.js#L126

I can't figure out when targetUrl is set on the session object - is it still necessary?

**Comment by cadecairos** [comment]
Lets add JSHint to automatically check the code for issues - most likely it will surface some buried problems. Not sure how you'd like to se this up, but elsewhere we're using gulp. see https://github.com/MozillaFoundation/mofo-example-app/blob/f125c4ca4ed1ed293c380d35a4e9af8d49908f9a/Gulpfile.js

**Comment by adamlofting** [comment]
Thanks @cadecairos !

> extraTemplateValues and its accompanying code don't appear to ever get used, can it be axed?

Good call. I cannot remember why that is there :stuck_out_tongue_closed_eyes: 

> I can't figure out when targetUrl is set on the session object - is it still necessary?

This is stored if you try to access a restricted route and get redirected to login. https://github.com/mozilla/webmaker-metrics/blob/master/app.js#L81 Then if you successfully login, you go back to where you were trying to get to.

> JSHint

I'll have a look at gulp now. I've been using the [jshint highlighting](https://github.com/mozilla/webmaker-metrics/blob/master/.jshintrc) in Sublime to keep an eye on things, but I don't have something like gulp in place for a project wide check.

**Comment by adamlofting** [comment]
@cadecairos gulp / jshint is in place now and isn't throwing any new errors up for me.

Let me know if you'd like to spend any more time in this app, or feel free to close this ticket now. Thanks again for your time on this.
